import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"}; const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const adminRoles=["admin","administrator","eier","firmaadmin"], sysRoles=["sysadm","sysadmin","systemadmin"];
Deno.serve(async req=>{ if(req.method==="OPTIONS")return new Response("ok",{headers:cors}); if(req.method!=="POST")return out({error:"Bruk POST."},405);
 const url=Deno.env.get("SUPABASE_URL")||"", sk=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"", ak=Deno.env.get("SUPABASE_ANON_KEY")||"", token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim(); if(!url||!sk||!ak||!token)return out({error:"Mangler konfigurasjon eller innlogging."},401);
 const svc=createClient(url,sk,{auth:{persistSession:false}}), uc=createClient(url,ak,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}}); const {data:u,error:ue}=await uc.auth.getUser(token); const email=String(u?.user?.email||"").toLowerCase(); if(ue||!email)return out({error:"Ugyldig innlogging."},401);
 const {data:a}=await svc.from("hand_ansatt").select("rolle,aktiv,firma_id").ilike("epost",email).eq("aktiv",true).limit(1).maybeSingle(); const {data:s}=await svc.from("hand_sysadm").select("id").ilike("epost",email).eq("aktiv",true).limit(1).maybeSingle(); const role=String(a?.rolle||"").toLowerCase(), isSys=!!s||sysRoles.includes(role); if(!isSys&&!adminRoles.includes(role))return out({error:"Kun admin eller sysadmin kan restore."},403);
 const b=await req.json().catch(()=>({})); const path=String(b?.path||""), firmaId=String(b?.firma_id||a?.firma_id||""); if(!path||!firmaId)return out({error:"Mangler backup eller firma."},400); if(!isSys&&firmaId!==String(a?.firma_id||""))return out({error:"Du kan bare restore eget firma."},403); if(String(b?.confirm||"")!==`RESTORE ${firmaId}`)return out({error:"Bekreftelsestekst er feil."},400);
 const {data:file,error:de}=await svc.storage.from("handverker-backups").download(path); if(de||!file)return out({error:"Kunne ikke lese backup: "+(de?.message||"")},500); const backup=JSON.parse(await file.text()); const tabs=backup.tabeller||backup.tables||{};
 const prePath=`pre-restore/${new Date().toISOString().slice(0,10)}/before-${Date.now()}-${firmaId}.json`; await svc.storage.from("handverker-backups").upload(prePath,JSON.stringify({laget:new Date().toISOString(),firma_id:firmaId,kilde:path}),{contentType:"application/json",upsert:false}).catch(()=>null);
 const order=Object.keys(tabs), results:any={}; for(const t of order){ const rows=Array.isArray(tabs[t])?tabs[t]:[]; let selected=rows.filter((r:any)=>t==="hand_firma"?String(r.id)===firmaId:String(r.firma_id||"")===firmaId); if(!selected.length)continue; const {error}=await svc.from(t).upsert(selected,{onConflict:"id"}); results[t]=error?{error:error.message,count:0}:{count:selected.length}; }
 await svc.from("hand_backup_restore_log").insert({bruker_epost:email,rolle:role,firma_id:firmaId,backup_path:path,handling:"firma_restore",status:Object.values(results).some((x:any)=>x.error)?"delvis":"ok",detaljer:results}); return out({ok:true,firma_id:firmaId,path,pre_restore_path:prePath,results}); });
