import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};const out=(b:unknown,s=200)=>new Response(JSON.stringify(b,null,2),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const adminRoles=["admin","administrator","eier","firmaadmin"],sysRoles=["sysadm","sysadmin","systemadmin"];
const RELATIONS:Record<string,Array<[string,string]>>={hand_time_bilde:[["time_id","hand_time"]],hand_faktura_vare:[["faktura_id","hand_faktura"]],hand_faktura_utlegg:[["faktura_id","hand_faktura"]],hand_tilbud_linje:[["tilbud_id","hand_tilbud"]],hand_tilbud_vedlegg:[["tilbud_id","hand_tilbud"]],hand_ansatt_trekk:[["ansatt_id","hand_ansatt"],["trekk_type_id","hand_trekk_type"]],hand_arbeidsordre_tildeling:[["arbeidsordre_id","hand_arbeidsordre"]],hand_bil_vare:[["bil_id","hand_bil"],["vare_id","hand_vare"]]};
const TABLES=["hand_firma","hand_firma_bruker","hand_ansatt","hand_kunde","hand_kunde_moduler","hand_prosjekt","hand_vare","hand_bil","hand_bil_lager","hand_bil_vare","hand_time","hand_time_bilde","hand_faktura","hand_faktura_vare","hand_faktura_utlegg","hand_tilbud","hand_tilbud_linje","hand_tilbud_vedlegg","hand_bilag","hand_fravaer","hand_lonnskjoring","hand_timebank","hand_trekk_type","hand_ansatt_trekk","hand_lager_bevegelse","hand_lagerlogg","hand_lager_bestilling","hand_bil_bestilling","hand_arbeidsordre","hand_arbeidsordre_tildeling","hand_innkjopsvarsel","hand_moduler"];

function filterFirma(all:Record<string,any[]>,firmaId:string){const selected:Record<string,any[]>={},ids:Record<string,Set<string>>={};for(const t of TABLES){const rows=all[t]||[];const picked=rows.filter((r:any)=>t==="hand_firma"?String(r?.id||"")===firmaId:String(r?.firma_id||"")===firmaId||(RELATIONS[t]||[]).some(([fk,parent])=>ids[parent]?.has(String(r?.[fk]||""))));selected[t]=picked;ids[t]=new Set(picked.map((r:any)=>String(r?.id||"")).filter(Boolean));}return selected;}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return out({error:"Bruk POST."},405);
 const url=Deno.env.get("SUPABASE_URL")||"",sk=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",ak=Deno.env.get("SUPABASE_ANON_KEY")||"",token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!url||!sk||!ak||!token)return out({error:"Mangler konfigurasjon eller innlogging."},401);
 const svc=createClient(url,sk,{auth:{persistSession:false}}),uc=createClient(url,ak,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const {data:u,error:ue}=await uc.auth.getUser(token);const email=String(u?.user?.email||"").toLowerCase();if(ue||!email)return out({error:"Ugyldig innlogging."},401);
 const {data:a}=await svc.from("hand_ansatt").select("rolle,aktiv,firma_id").ilike("epost",email).eq("aktiv",true).limit(1).maybeSingle();const {data:s}=await svc.from("hand_sysadm").select("id").ilike("epost",email).eq("aktiv",true).limit(1).maybeSingle();const role=String(a?.rolle||"").toLowerCase(),isSys=!!s||sysRoles.includes(role);if(!isSys&&!adminRoles.includes(role))return out({error:"Kun admin eller sysadmin kan restore."},403);
 const b=await req.json().catch(()=>({}));const path=String(b?.path||"");let firmaId=String(b?.firma_id||a?.firma_id||"");const restoreAll=isSys&&(b?.scope==="all"||firmaId==="__alle__");if(restoreAll)firmaId="";if(!path||(!restoreAll&&!firmaId))return out({error:"Mangler backup eller firma."},400);if(!isSys&&firmaId!==String(a?.firma_id||""))return out({error:"Du kan bare restore eget firma."},403);
 const expected=restoreAll?"RESTORE ALLE":`RESTORE ${firmaId}`;if(String(b?.confirm||"")!==expected)return out({error:"Bekreftelsestekst er feil."},400);
 const {data:file,error:de}=await svc.storage.from("handverker-backups").download(path);if(de||!file)return out({error:"Kunne ikke lese backup: "+(de?.message||"")},500);let backup:any;try{backup=JSON.parse(await file.text())}catch{return out({error:"Backupfilen er ikke gyldig JSON."},400)}const tabs=backup.tabeller||backup.tables||{};
 if(restoreAll&&backup.scope==="firma")return out({error:"En firmabackup kan ikke restores som ALLE."},400);if(!restoreAll&&backup.scope==="firma"&&backup.firma_id&&String(backup.firma_id)!==firmaId)return out({error:"Backupen tilhører et annet firma."},403);
 // Ta en ekte sikkerhetskopi av dagens data før restore.
 const current:any={},preErrors:any={};for(const t of TABLES){const {data,error}=await svc.from(t).select("*");current[t]=data||[];if(error)preErrors[t]=error.message;}
 const currentScoped=restoreAll?current:filterFirma(current,firmaId);
 const pre={type:"rett-i-lomma-pre-restore",versjon:3,laget:new Date().toISOString(),scope:restoreAll?"all":"firma",firma_id:firmaId||null,kilde:path,tabeller:currentScoped,errors:preErrors};const date=new Date().toISOString().slice(0,10),prePath=`pre-restore/${date}/before-${restoreAll?"alle":firmaId}-${Date.now()}.json`;const {error:pe}=await svc.storage.from("handverker-backups").upload(prePath,JSON.stringify(pre,null,2),{contentType:"application/json",upsert:false});if(pe)return out({error:"Kunne ikke lage pre-restore-backup: "+pe.message},500);
 const restoreTabs=restoreAll?tabs:filterFirma(tabs,firmaId);
 const results:any={};for(const t of TABLES){const rows=Array.isArray(restoreTabs[t])?restoreTabs[t]:[];if(!rows.length)continue;const {error}=await svc.from(t).upsert(rows,{onConflict:"id"});results[t]=error?{error:error.message,count:0}:{count:rows.length};}
 const failed=Object.values(results).some((x:any)=>x.error);await svc.from("hand_backup_restore_log").insert({bruker_epost:email,rolle:role,firma_id:firmaId||null,backup_path:path,handling:restoreAll?"all_restore":"firma_restore",status:failed?"delvis":"ok",detaljer:results});return out({ok:!failed,scope:restoreAll?"all":"firma",firma_id:firmaId||null,path,pre_restore_path:prePath,results});});
