-- Rett i Lomma Veterinaer: integrasjoner, migreringsimport og sporbarhet.
-- Kan kjøres flere ganger.

alter table if exists public.vet_dyreeiere
  add column if not exists ekstern_id text,
  add column if not exists importert_at timestamptz;

alter table if exists public.vet_dyr
  add column if not exists ekstern_id text,
  add column if not exists importert_at timestamptz;

alter table if exists public.vet_journal
  add column if not exists ekstern_id text,
  add column if not exists import_kilde text,
  add column if not exists importert_at timestamptz;

create unique index if not exists vet_dyreeiere_klinikk_ekstern_id_uq
  on public.vet_dyreeiere(klinikk_id, ekstern_id) where ekstern_id is not null;
create unique index if not exists vet_dyr_klinikk_ekstern_id_uq
  on public.vet_dyr(klinikk_id, ekstern_id) where ekstern_id is not null;
create unique index if not exists vet_journal_klinikk_ekstern_id_uq
  on public.vet_journal(klinikk_id, ekstern_id) where ekstern_id is not null;

create table if not exists public.vet_integrasjoner (
  id uuid primary key default gen_random_uuid(),
  klinikk_id uuid not null references public.vet_klinikker(id) on delete cascade,
  integrasjonstype text not null,
  leverandor text not null,
  klientnavn text,
  orgnummer text,
  synk_modus text not null default 'godkjent' check (synk_modus in ('godkjent','manuell')),
  ehf_aktiv boolean not null default true,
  aktiv boolean not null default true,
  tilkoblet boolean not null default false,
  ekstern_klient_id text,
  sist_kontrollert_at timestamptz,
  sist_synkronisert_at timestamptz,
  opprettet_at timestamptz not null default now(),
  oppdatert_at timestamptz not null default now(),
  unique (klinikk_id, integrasjonstype)
);

create table if not exists public.vet_integrasjon_logg (
  id bigint generated by default as identity primary key,
  klinikk_id uuid not null references public.vet_klinikker(id) on delete cascade,
  integrasjonstype text not null default 'regnskap',
  leverandor text,
  handling text not null,
  status text not null,
  referanse text,
  ekstern_referanse text,
  melding text,
  detaljer jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists vet_integrasjon_logg_klinikk_tid_idx on public.vet_integrasjon_logg(klinikk_id, created_at desc);

create table if not exists public.vet_import_logg (
  id bigint generated by default as identity primary key,
  klinikk_id uuid not null references public.vet_klinikker(id) on delete cascade,
  filnavn text,
  antall_kunder integer not null default 0,
  antall_dyr integer not null default 0,
  antall_journaler integer not null default 0,
  duplikater_hoppet_over integer not null default 0,
  status text not null,
  detaljer jsonb not null default '{}'::jsonb,
  opprettet_av uuid default auth.uid(),
  created_at timestamptz not null default now()
);
create index if not exists vet_import_logg_klinikk_tid_idx on public.vet_import_logg(klinikk_id, created_at desc);

-- Hemmeligheter leses aldri fra nettleseren. Kun Edge Function med service-role
-- kan bruke denne tabellen. RLS har med hensikt ingen klientpolicyer.
create table if not exists public.vet_integrasjon_hemmeligheter (
  klinikk_id uuid not null references public.vet_klinikker(id) on delete cascade,
  leverandor text not null,
  hemmelighet jsonb not null,
  oppdatert_at timestamptz not null default now(),
  primary key (klinikk_id, leverandor)
);

alter table public.vet_integrasjoner enable row level security;
alter table public.vet_integrasjon_logg enable row level security;
alter table public.vet_import_logg enable row level security;
alter table public.vet_integrasjon_hemmeligheter enable row level security;

drop policy if exists vet_integrasjoner_admin_select on public.vet_integrasjoner;
create policy vet_integrasjoner_admin_select on public.vet_integrasjoner for select to authenticated using (
  public.vet_is_systemadmin() or
  (klinikk_id = public.vet_current_klinikk_id() and public.vet_is_klinikk_admin())
);
drop policy if exists vet_integrasjoner_admin_insert on public.vet_integrasjoner;
create policy vet_integrasjoner_admin_insert on public.vet_integrasjoner for insert to authenticated with check (
  public.vet_is_systemadmin() or
  (klinikk_id = public.vet_current_klinikk_id() and public.vet_is_klinikk_admin())
);
drop policy if exists vet_integrasjoner_admin_update on public.vet_integrasjoner;
create policy vet_integrasjoner_admin_update on public.vet_integrasjoner for update to authenticated using (
  public.vet_is_systemadmin() or
  (klinikk_id = public.vet_current_klinikk_id() and public.vet_is_klinikk_admin())
) with check (
  public.vet_is_systemadmin() or
  (klinikk_id = public.vet_current_klinikk_id() and public.vet_is_klinikk_admin())
);

drop policy if exists vet_integrasjon_logg_admin_select on public.vet_integrasjon_logg;
create policy vet_integrasjon_logg_admin_select on public.vet_integrasjon_logg for select to authenticated using (
  public.vet_is_systemadmin() or
  (klinikk_id = public.vet_current_klinikk_id() and public.vet_is_klinikk_admin())
);
drop policy if exists vet_integrasjon_logg_same_clinic_insert on public.vet_integrasjon_logg;
create policy vet_integrasjon_logg_same_clinic_insert on public.vet_integrasjon_logg for insert to authenticated with check (
  public.vet_is_systemadmin() or klinikk_id = public.vet_current_klinikk_id()
);

drop policy if exists vet_import_logg_admin_select on public.vet_import_logg;
create policy vet_import_logg_admin_select on public.vet_import_logg for select to authenticated using (
  public.vet_is_systemadmin() or
  (klinikk_id = public.vet_current_klinikk_id() and public.vet_is_klinikk_admin())
);
drop policy if exists vet_import_logg_admin_insert on public.vet_import_logg;
create policy vet_import_logg_admin_insert on public.vet_import_logg for insert to authenticated with check (
  public.vet_is_systemadmin() or
  (klinikk_id = public.vet_current_klinikk_id() and public.vet_is_klinikk_admin())
);

revoke all on public.vet_integrasjon_hemmeligheter from anon, authenticated;
grant select, insert, update on public.vet_integrasjoner to authenticated;
grant select, insert on public.vet_integrasjon_logg to authenticated;
grant select, insert on public.vet_import_logg to authenticated;

comment on table public.vet_integrasjoner is 'Ikke-hemmelig integrasjonsoppsett per klinikk.';
comment on table public.vet_integrasjon_hemmeligheter is 'Leverandørtilgang. Kun service-role/Edge Function.';
comment on table public.vet_import_logg is 'Sporbar logg over migreringsimport av kunder, dyr og journaler.';
